version: '3'

services:
  rabbitmq:
    container_name: api-rabbitmq
    image: 'rabbitmq:3.8-management'
    restart: always
    ports:
      - '15672:15672'
      - '5672:5672'
    volumes:
      - './.rabbitmq_data:/var/lib/rabbitmq/mnesia'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  
  postgres:
    container_name: api-postgres
    image: 'postgres'
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rabbitmq
    volumes:
      - ./postgres/data:/var/lib/postgresql/data